[package]
name = "raw2nii-py"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "raw2nii"
crate-type = ["cdylib", "rlib"]

[dependencies]
raw2nii-core = { path = "../raw2nii-core" }
raw2nii-ge = { path = "../raw2nii-ge" }
ndarray.workspace = true
num-complex.workspace = true
serde_json.workspace = true
tracing.workspace = true
pyo3 = { version = "0.22", features = ["abi3-py39"] }
numpy = "0.22"
pythonize = "0.22"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
