[package]
name = "raw2nii-ge"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
raw2nii-core = { path = "../raw2nii-core" }
ndarray.workspace = true
num-complex.workspace = true
thiserror.workspace = true
tracing.workspace = true
hdf5-metno = { version = "0.10", features = ["static"] }
